ItemNames:
	db "Masterbola@"
	db "Ultrabola@"
	db "Superbola@"
	db "Pokébola@"
	db "Mapa@"
	db "Bicicleta@"
	db "SURFBOARD@"	;joenote - give the surfboard it's fan name instead of ?????
	db "Safaribola@"
	db "POKéDEX@"
	db "Piedra Lunar@"
	db "Antídoto@"
	db "Antiquema@"
	db "Antihielo@"
	db "Despertar@"
	db "Antiparali@"
	db "CuraciónTotal@"
	db "PociónMáxima@"
	db "Hiperpoción@"
	db "Superpoción@"
	db "Poción@"
	db "Roca@"
	db "Cascada@"
	db "Trueno@"
	db "Arcoíris@"
	db "Alma@"
	db "Pantano@"
	db "Volcán@"
	db "Tierra@"
	db "Cuerda huida@"
	db "Repelente@"
	db "Ámbar Viejo@"
	db "Piedra Fuego@"
	db "Piedra Trueno@"
	db "Piedra Agua@"
	db "Más PS@"
	db "Proteína@"
	db "Hierro@"
	db "Carbohidratos@"
	db "Calcio@"
	db "Caramelo Raro@"
	db "Fósil Domo@"
	db "Fósil Helix@"
	db "Llave Secreta@"
;	db "?????@"
	db "MIST STONE@"	;joenote - custom item
	db "Cupón Bici@"
	db "Precisión X@"
	db "Piedra Hoja@"
	db "Tar. Acceso@"
	db "Pepita de Oro@"
	;db "Más PP@"	;unused PP_UP
	db "M.GENE@"	;joenote - custom item
	db "Pokémuñeca@"
	db "CuraciónTotal@"
	db "Revivir@"
	db "RevivirMáximo@"
	db "Protec. Esp.@"
	db "Superepelente@"
	db "Repel. Máximo@"
	db "Directo@"
	db "Moneda@"
	db "Agua Fresca@"
	db "Refresco@"
	db "Limonada@"
	db "BoletoBarco@"
	db "DentaduraOro@"
	db "Ataque X@"
	db "Defensa X@"
	db "Velocidad X@"
	db "Especial X@"
	db "Monedero@"
	db "PaqueteOak@"
	db "Zahorí@"
	db "Visor Silph@"
	db "Pokéflauta@"
	db "LlaveElevador@"
	db "Repartir Exp@"
	db "Caña Vieja@"
	db "Caña Buena@"
	db "Supercaña @"
	db "Más PP@"
	db "Éter@"
	db "Éter Máximo@"
	db "Elixir@"
	db "Elixir Máximo@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
