MoveNames::
	db "Destructor@"
	db "Golpe Karate@"
	db "Doble Bofetón@"
	db "Puño Cometa@"
	db "Megapuño@"
	db "Día De Pago@"
	db "Puño Fuego@"
	db "Puño Hielo@"
	db "Puño Trueno@"
	db "Arañazo@"
	db "Fuerza Garra@"
	db "Guillotina@"
	db "Viento Cort.@"
	db "Danza Espadas@"
	db "Corte@"
	db "Ráfaga@"
	db "Ataque De Ala@"
	db "Torbellino@"
	db "Vuelo@"
	db "Atadura@"
	db "Golpazo@"
	db "Látigo Cepa@"
	db "Estampida@"
	db "Doble Patada@"
	db "Megapatada@"
	db "Patada Salto@"
	db "PatadaRodante@"
	db "Ataque Arena@"
	db "Golpe Cabeza@"
	db "Ataque Cuerno@"
	db "Ataque Furia@"
	db "Cuer. Taladro@"
	db "Tacleada@"
	db "Golpe Cuerpo@"
	db "Envoltura@"
	db "Derribo@"
	db "Golpiza@"
	db "Doble Filo@"
	db "Látigo Cola@"
	db "Piquete Ven.@"
	db "Doble Aguijón@"
	db "Misil Aguja@"
	db "Malicioso@"
	db "Mordida@"
	db "Gruñido@"
	db "Rugido@"
	db "Canto@"
	db "Supersónico@"
	db "Explo. Sónica@"
	db "Anulación@"
	db "Ácido@"
	db "Brasas@"
	db "Lanzallamas@"
	db "Neblina@"
	db "Chorro Agua@"
	db "Hidrobomba@"
	db "Surf@"
	db "Rayo De Hielo@"
	db "Ventisca@"
	db "Psicorrayo@"
	db "Rayo Burbuja@"
	db "Rayo Aurora@"
	db "Hiperrayo@"
	db "Picotazo@"
	db "Pico Taladro@"
	db "Sumisión@"
	db "Patada Baja@"
	db "Contraataque@"
	db "Mov. Sísmico@"
	db "Fuerza@"
	db "Absorción@"
	db "Megadrenado@"
	db "Drenadoras@"
	db "Crecimiento@"
	db "Hojas Navaja@"
	db "Rayo Solar@"
	db "Polvo Veneno@"
	db "Paralizador@"
	db "Somnífero@"
	db "Danza Pétalos@"
	db "Disparo Seda@"
	db "Furia Dragón@"
	db "Giro Fuego@"
	db "Impactrueno@"
	db "Atactrueno@"
	db "Onda Trueno@"
	db "Trueno@"
	db "Lanzarrocas@"
	db "Terremoto@"
	db "Fisura@"
	db "Excavar@"
	db "Tóxico@"
	db "Confusión@"
	db "Fuerza Psí.@"
	db "Hipnosis@"
	db "Meditación@"
	db "Agilidad@"
	db "Ataque Rápido@"
	db "Furia@"
	db "Teletransp.@"
	db "Tinieblas@"
	db "Mímica@"
	db "Chillido@"
	db "Doble Equipo@"
	db "Recuperación@"
	db "Fortaleza@"
	db "Reducción@"
	db "Pantalla Humo@"
	db "Rayo Confu.@"
	db "Refugio@"
	db "Hacerse Bola@"
	db "Barrera@"
	db "Pantalla Luz@"
	db "Niebla@"
	db "Reflejo@"
	db "Centrar Ener.@"
	db "Venganza@"
	db "Metrónomo@"
	db "Mov. Espejo@"
	db "Autodestruc.@"
	db "Bomba Huevo@"
	db "Lengüetazo@"
	db "Humo@"
	db "Lodo@"
	db "Golpe Hueso@"
	db "Llamarada@"
	db "Cascada@"
	db "Fuerza Garra@"
	db "Meteoros@"
	db "Megatope@"
	db "Cañón Picos@"
	db "Apretón@"
	db "Amnesia@"
	db "Kinético@"
	db "Ovocuración@"
	db "Patada S.Alta@"
	db "Fulmirada@"
	db "Comesueños@"
	db "Gas venenoso@"
	db "Bombardeo@"
	db "Chupavidas@"
	db "Beso De Amor@"
	db "Ataque Celes.@"
	db "Transform.@"
	db "Burbuja@"
	db "Puño Mareo@"
	db "Esporas@"
	db "Destello@"
	db "Psicoonda@"
	db "Salpicadura@"
	db "Armad. Ácida@"
	db "Martillazo@"
	db "Explosión@"
	db "Golpes Furia@"
	db "Huesomerang@"
	db "Descanso@"
	db "Pedrada@"
	db "Hipercolmillo@"
	db "Afilar@"
	db "Conversión@"
	db "Triataque@"
	db "Supercolmillo@"
	db "Cuchillada@"
	db "Sustituto@"
	db "Forcejeo@"

